# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Covid-19-DataViz' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Covid-19-DataViz
  pod "Macaw", "0.9.6"
  pod "Alamofire", "~> 5.0"
  pod 'SwiftyJSON'
end
